export const WINDOW_SPACING_PIXELS = 8;
export const WINDOW_SPACING05 = WINDOW_SPACING_PIXELS / 2;
export const WINDOW_SPACING1 = WINDOW_SPACING_PIXELS * 1;
export const WINDOW_SPACING2 = WINDOW_SPACING_PIXELS * 2;
export const WINDOW_SPACING4 = WINDOW_SPACING_PIXELS * 4;
