export enum TriggeringEventType {
    MISSION_VICTORY = "MISSION_VICTORY",
    MISSION_DEFEAT = "MISSION_DEFEAT",
    START_OF_TURN = "START_OF_TURN",
    SQUADDIE_IS_INJURED = "SQUADDIE_IS_INJURED",
    SQUADDIE_IS_DEFEATED = "SQUADDIE_IS_DEFEATED",
}
