export const TrashRobotLookForTrashActionEnum = {
    UNKNOWN: "UNKNOWN",
    TRIGGER_INITIALIZED: "TRIGGER_INITIALIZED",
    TRIGGER_SEEN_TRASH: "TRIGGER_SEEN_TRASH",
    TRIGGER_PICKED_UP_TRASH: "TRIGGER_PICKED_UP_TRASH",
    TRIGGER_THREW_TRASH_IN_COMPACTOR: "TRIGGER_THREW_TRASH_IN_COMPACTOR",
    INITIALIZED: "INITIALIZED",
    INITIALIZED_EXIT: "INITIALIZED_EXIT",
    SEARCH_FOR_TRASH_ENTRY: "SEARCH_FOR_TRASH_ENTRY",
    SEARCH_FOR_TRASH: "SEARCH_FOR_TRASH",
    SEARCH_FOR_TRASH_EXIT: "SEARCH_FOR_TRASH_EXIT",
    HEAD_FOR_TRASH_ENTRY: "HEAD_FOR_TRASH_ENTRY",
    HEAD_FOR_TRASH: "HEAD_FOR_TRASH",
    HEAD_FOR_TRASH_EXIT: "HEAD_FOR_TRASH_EXIT",
    HEAD_FOR_COMPACTOR_ENTRY: "HEAD_FOR_COMPACTOR_ENTRY",
    HEAD_FOR_COMPACTOR: "HEAD_FOR_COMPACTOR",
    HEAD_FOR_COMPACTOR_EXIT: "HEAD_FOR_COMPACTOR_EXIT",
} as const satisfies Record<string, string>

export type TTrashRobotLookForTrashAction = EnumLike<
    typeof TrashRobotLookForTrashActionEnum
>
